/*
 * Copyright (c) 2026 Johan Stenstam, johani@johani.org
 *
 * Everything this tool writes: child zone files, the parent zone file (with
 * the children's DS records already in it), the tdns-auth config block, and
 * the snippet for the grandparent that this tool deliberately does NOT apply.
 */

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/miekg/dns"
)

// Tree is one fully-resolved generation: the parent, its children, and the DS
// records collected for each. Built once by the generate path and then handed
// to the emitters, so nothing below has to talk to a server.
type Tree struct {
	Conf     *Config
	Serial   uint32
	Children []Child
	// ParentDS is the parent zone's own DS, for the grandparent snippet.
	ParentDS []string
}

// Child is one generated leaf zone.
type Child struct {
	Combo Combo
	Label string
	Name  string   // FQDN
	DS    []string // DS rdata, one per KSK
}

// NewSerial is the SOA serial for this run: YYYYMMDDNN. Regenerated every run,
// so a re-generate always supersedes what a secondary already has -- at the
// cost of a diff on every zone file, which is the trade we chose.
func NewSerial(now time.Time) uint32 {
	var s uint32
	fmt.Sscanf(now.UTC().Format("2006010200"), "%d", &s)
	return s
}

// ZonefilePath is where a zone's file goes, and equally what the generated
// tdns-auth config will point at. One function so the two cannot disagree.
func (t *Tree) ZonefilePath(zone string) string {
	return filepath.Join(t.Conf.Zonegen.Output.ZoneDir,
		fmt.Sprintf(t.Conf.Zonegen.Output.ZoneFilePattern, zone))
}

// childZonefile renders one leaf. Every child carries a self-describing apex
// TXT: in a tree of a hundred near-identical zones, being able to ask a zone
// what it is turns out to matter more than anything else in it.
func (t *Tree) childZonefile(c Child) string {
	z := &t.Conf.Zonegen
	var b strings.Builder

	fmt.Fprintf(&b, "; Generated by %s -- do not edit by hand.\n", appName)
	fmt.Fprintf(&b, "; KSK %s / ZSK %s\n", c.Combo.KSK, c.Combo.ZSK)
	fmt.Fprintf(&b, "%s\t%d\tIN\tSOA\t%s %s ( %d 3600 600 1209600 600 )\n",
		c.Name, defaultTTL, z.Parent.Nameservers[0], z.Parent.Rname, t.Serial)
	for _, ns := range z.Parent.Nameservers {
		fmt.Fprintf(&b, "%s\t%d\tIN\tNS\t%s\n", c.Name, defaultTTL, ns)
	}
	fmt.Fprintf(&b, "%s\t%d\tIN\tTXT\t%q\n", c.Name, defaultTTL, describeCombo(c.Combo))
	for _, addr := range z.Children.Addresses {
		fmt.Fprintf(&b, "%s\t%d\tIN\t%s\t%s\n", c.Name, defaultTTL, addressRRType(addr), addr)
	}
	for _, rec := range z.Children.Records {
		// Expanded through the parser rather than copied verbatim, so a
		// config line like "www IN A 192.0.2.2" comes out fully qualified
		// like everything else here. Validated at config load, so an error
		// now is not reachable -- but silently emitting a bad line would be
		// worse than saying so.
		expanded, err := expandRecord(c.Name, rec)
		if err != nil {
			fmt.Fprintf(&b, "; SKIPPED unparsable record %q: %v\n", rec, err)
			continue
		}
		fmt.Fprintf(&b, "%s\n", expanded)
	}
	return b.String()
}

// expandRecord parses one config-supplied record against its zone origin and
// returns it fully qualified. Shared with config validation so the check and
// the output cannot disagree about what a record means.
func expandRecord(origin, rec string) (string, error) {
	rr, err := dns.NewRR(fmt.Sprintf("$ORIGIN %s\n$TTL %d\n%s", origin, defaultTTL, rec))
	if err != nil {
		return "", err
	}
	if rr == nil {
		return "", fmt.Errorf("no record")
	}
	return rr.String(), nil
}

// parentZonefile renders the parent, delegations and DS included. The DS
// records are already here rather than collected by a second pass, which is
// the whole reason this tool creates the keys itself.
func (t *Tree) parentZonefile() string {
	z := &t.Conf.Zonegen
	var b strings.Builder

	fmt.Fprintf(&b, "; Generated by %s -- do not edit by hand.\n", appName)
	fmt.Fprintf(&b, "%s\t%d\tIN\tSOA\t%s %s ( %d 3600 600 1209600 600 )\n",
		z.Parent.Name, defaultTTL, z.Parent.Nameservers[0], z.Parent.Rname, t.Serial)
	for _, ns := range z.Parent.Nameservers {
		fmt.Fprintf(&b, "%s\t%d\tIN\tNS\t%s\n", z.Parent.Name, defaultTTL, ns)
	}
	for _, addr := range z.Parent.Addresses {
		fmt.Fprintf(&b, "%s\t%d\tIN\t%s\t%s\n", z.Parent.Name, defaultTTL, addressRRType(addr), addr)
	}
	fmt.Fprintf(&b, "%s\t%d\tIN\tTXT\t%q\n", z.Parent.Name, defaultTTL,
		fmt.Sprintf("PQ-DNSSEC testbed: one child zone per KSK/ZSK algorithm pair. See <ksk>-<zsk>.%s",
			strings.TrimSuffix(z.Parent.Name, ".")))
	b.WriteString("\n")

	for _, c := range t.Children {
		for _, ns := range z.Parent.Nameservers {
			fmt.Fprintf(&b, "%s\t%d\tIN\tNS\t%s\n", c.Name, defaultTTL, ns)
		}
		for _, ds := range c.DS {
			fmt.Fprintf(&b, "%s\t%d\tIN\tDS\t%s\n", c.Name, defaultTTL, ds)
		}
	}
	return b.String()
}

// authConfig renders the tdns-auth block: one DNSSEC policy per algorithm
// pair, the split_algorithms allowlist those pairs require, the derived
// large_algorithms list, and a zone declaration per zone.
//
// This is emitted as a block to merge into the server's config rather than a
// file to include:, because tdns-auth's include: merge overrides list-valued
// keys wholesale -- an included file carrying zones: would silently replace
// every other zone the server has.
func (t *Tree) authConfig() string {
	z := &t.Conf.Zonegen
	parentCombo := Combo{KSK: z.Parent.KSK, ZSK: z.Parent.ZSK}
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by %s -- do not edit by hand.\n", appName)
	fmt.Fprintf(&b, "# Merge these blocks into the tdns-auth config; do NOT pull this in with\n")
	fmt.Fprintf(&b, "# include:, whose merge would replace the server's own zones: list.\n\n")

	b.WriteString("dnssec:\n")
	if large := largeAlgorithms(z.Children.Combos, parentCombo); len(large) > 0 {
		fmt.Fprintf(&b, "   large_algorithms:  [ %s ]\n", strings.Join(large, ", "))
	}
	if split := splitAlgorithms(z.Children.Combos, parentCombo); len(split) > 0 {
		b.WriteString("   split_algorithms:\n")
		ksks := make([]string, 0, len(split))
		for k := range split {
			ksks = append(ksks, k)
		}
		sort.Strings(ksks)
		for _, ksk := range ksks {
			fmt.Fprintf(&b, "      %s:  [ %s ]\n", ksk, strings.Join(split[ksk], ", "))
		}
	}

	b.WriteString("   policies:\n")
	for _, c := range allCombos(z) {
		fmt.Fprintf(&b, "      %s:\n", c.PolicyName())
		fmt.Fprintf(&b, "         algorithm:  %s\n", c.ZSK)
		b.WriteString("         mode:       ksk-zsk\n")
		b.WriteString("         ksk:\n")
		fmt.Fprintf(&b, "            algorithm:  %s\n", c.KSK)
		b.WriteString("            lifetime:   forever\n")
		b.WriteString("         zsk:\n")
		fmt.Fprintf(&b, "            algorithm:  %s\n", c.ZSK)
		b.WriteString("            lifetime:   forever\n")
		b.WriteString("         csk:\n")
		b.WriteString("            lifetime:  none\n")
		// Required by tdns-auth: a policy without sigvalidity.default is
		// rejected at parse time and every zone bound to it is unusable.
		b.WriteString("         sigvalidity:\n")
		fmt.Fprintf(&b, "            default:  %s\n", z.SigValidity.Default)
		fmt.Fprintf(&b, "            dnskey:   %s\n", z.SigValidity.Dnskey)
		fmt.Fprintf(&b, "            ds:       %s\n", z.SigValidity.DS)
	}

	// Zone declarations come from the CONFIG, not from t.Children. Nothing in
	// a zone declaration depends on anything the server told us, so deriving
	// them from the collected DS results would only couple this to a fully
	// populated Tree -- and let the two lists drift apart.
	b.WriteString("\nzones:\n")
	t.writeZoneDecl(&b, z.Parent.Name, parentCombo.PolicyName())
	for _, c := range z.Children.Combos {
		t.writeZoneDecl(&b, c.Label(z.Children.Label)+"."+z.Parent.Name, c.PolicyName())
	}
	return b.String()
}

func (t *Tree) writeZoneDecl(b *strings.Builder, zone, policy string) {
	fmt.Fprintf(b, "   - name:          %s\n", zone)
	b.WriteString("     type:          primary\n")
	fmt.Fprintf(b, "     zonefile:      %s\n", t.ZonefilePath(zone))
	b.WriteString("     store:         map\n")
	b.WriteString("     options:       [ online-signing ]\n")
	fmt.Fprintf(b, "     dnssecpolicy:  %s\n", policy)
}

// allCombos is every pair a policy is needed for: the children's, plus the
// parent's own, deduplicated (the parent commonly reuses a child's pair).
func allCombos(z *ZonegenConf) []Combo {
	seen := map[string]bool{}
	var out []Combo
	for _, c := range append(append([]Combo{}, z.Children.Combos...),
		Combo{KSK: z.Parent.KSK, ZSK: z.Parent.ZSK}) {
		if seen[c.PolicyName()] {
			continue
		}
		seen[c.PolicyName()] = true
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].PolicyName() < out[j].PolicyName() })
	return out
}

// DelegationSnippet is what the operator pastes into the PARENT of our parent
// -- typically a zone served by something else entirely (BIND, in the training
// lab). This tool prints it and stops: reaching into another nameserver's zone
// files is not its business.
func (t *Tree) DelegationSnippet() string {
	z := &t.Conf.Zonegen
	var b strings.Builder
	fmt.Fprintf(&b, "; Add to the parent of %s, then reload it.\n", z.Parent.Name)
	for _, ns := range z.Parent.Nameservers {
		fmt.Fprintf(&b, "%s\tIN\tNS\t%s\n", z.Parent.Name, ns)
	}
	for _, ds := range t.ParentDS {
		fmt.Fprintf(&b, "%s\tIN\tDS\t%s\n", z.Parent.Name, ds)
	}
	if len(t.ParentDS) == 0 {
		b.WriteString("; (no DS: the parent zone has no KSK in the keystore yet)\n")
	}
	return b.String()
}

// writeFile writes atomically via temp+rename, so a crash or a full disk
// cannot leave a half-written zone file that the server would happily load.
func writeFile(path, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating %s: %v", dir, err)
	}
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp")
	if err != nil {
		return fmt.Errorf("temp file in %s: %v", dir, err)
	}
	tmpPath := tmp.Name()
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("writing %s: %v", tmpPath, err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("syncing %s: %v", tmpPath, err)
	}
	if err := tmp.Chmod(0644); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("chmod %s: %v", tmpPath, err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("closing %s: %v", tmpPath, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("renaming to %s: %v", path, err)
	}
	return nil
}
