/*
 * Copyright (c) 2026 Johan Stenstam, johani@johani.org
 *
 * The tree generator: a delegated hierarchy of ordinary zones.
 *
 * This is pqtree with the algorithm matrix taken out -- a parent, its children,
 * their children, each a real zone with its own keys and a DS in its parent.
 * The names are pronounceable rather than derived from anything, because here
 * there is nothing to derive them from.
 *
 * The whole DS-into-parent path is shared with pqtree via the back half, so
 * what this file actually contains is only the shape of the tree.
 */

package main

import (
	"fmt"
	"strings"

	"github.com/miekg/dns"
	"github.com/spf13/cobra"
)

func treeCmd() *cobra.Command {
	var (
		opts     runOptions
		depth    int
		breadth  int
		kskAlg   string
		zskAlg   string
		unsigned bool
	)
	c := &cobra.Command{
		Use:   "tree",
		Short: "A delegated hierarchy of ordinary zones",
		Long: `Generates a tree of delegated zones: an apex, --breadth children under it,
--breadth children under each of those, and so on to --depth.

Every zone is signed with the same policy and carries a DS in its parent, so
the chain validates from the apex down without a second pass. Zone count grows
as breadth^depth, so --plan first.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			conf, err := loadForRun(&opts)
			if err != nil {
				return err
			}
			if opts.Zone == "" {
				return fmt.Errorf("--zone is required: it is the apex of the tree")
			}
			if depth < 1 || breadth < 1 {
				return fmt.Errorf("--depth and --breadth must both be at least 1")
			}
			if err := conf.RequireOutput(opts.OutFile == ""); err != nil {
				return err
			}
			zs, err := buildTree(conf, dns.Fqdn(opts.Zone), depth, breadth,
				kskAlg, zskAlg, unsigned)
			if err != nil {
				return err
			}
			return runGenerate(conf, zs, &opts)
		},
	}
	opts.addCommonFlags(c)
	c.Flags().IntVar(&depth, "depth", 2, "levels of delegation below the apex")
	c.Flags().IntVar(&breadth, "breadth", 3, "child zones per zone")
	c.Flags().StringVar(&kskAlg, "ksk", "ED25519", "KSK algorithm")
	c.Flags().StringVar(&zskAlg, "zsk", "ED25519", "ZSK algorithm")
	c.Flags().BoolVar(&unsigned, "unsigned", false, "generate unsigned zones (no keystore contact)")
	return c
}

func buildTree(c *Config, apex string, depth, breadth int,
	kskAlg, zskAlg string, unsigned bool) (*ZoneSet, error) {

	d := &c.Zonegen.Defaults
	policy := ""
	var policies []PolicySpec
	if !unsigned {
		kskAlg, zskAlg = strings.ToUpper(kskAlg), strings.ToUpper(zskAlg)
		if err := validateCombo(Combo{KSK: kskAlg, ZSK: zskAlg}, "--ksk/--zsk"); err != nil {
			return nil, err
		}
		policy = strings.ToLower(kskAlg + "-" + zskAlg)
		policies = []PolicySpec{{
			Name: policy, KSKAlg: kskAlg, ZSKAlg: zskAlg,
			Mode: "ksk-zsk", KSKLife: "forever", ZSKLife: "forever",
		}}
	}

	ns, rname := treeServerNames(c, apex)
	zs := &ZoneSet{Nameservers: ns, Rname: rname, Apex: apex, Policies: policies}

	// Breadth-first, so the parent of every zone is already in the set when its
	// children are appended and Children can be filled in by index.
	type pending struct {
		name  string
		level int
		index int // position in zs.Zones
	}
	zs.Zones = append(zs.Zones, ZoneSpec{Name: apex, Policy: policy,
		Records: treeApexRecords(apex, d)})
	queue := []pending{{apex, 0, 0}}

	var counter uint64
	for len(queue) > 0 {
		cur := queue[0]
		queue = queue[1:]
		if cur.level >= depth {
			continue
		}
		for b := 0; b < breadth; b++ {
			child := Label(counter) + "." + cur.name
			counter++
			zs.Zones = append(zs.Zones, ZoneSpec{
				Name: child, Policy: policy, Records: treeApexRecords(child, d),
			})
			zs.Zones[cur.index].Children = append(zs.Zones[cur.index].Children, child)
			queue = append(queue, pending{child, cur.level + 1, len(zs.Zones) - 1})
		}
	}
	zs.AddGlue(&c.Zonegen.Defaults)
	return zs, nil
}

// treeApexRecords is the minimum that makes a generated zone answer something
// other than SOA and NS: one TXT saying what it is.
func treeApexRecords(zone string, d *DefaultsConf) []string {
	return []string{fmt.Sprintf("%s\t%d\tIN\tTXT\t%q", zone, d.TTL,
		"generated by "+appName)}
}

// treeServerNames borrows the pqtree parent's nameservers when the config
// happens to declare them, and otherwise synthesises in-bailiwick ones. A
// generated tree still needs SOMETHING in its NS set, and a name under the apex
// is the one choice that is always valid without asking.
func treeServerNames(c *Config, apex string) (ns []string, rname string) {
	p := &c.Zonegen.Pqtree.Parent
	if len(p.Nameservers) > 0 {
		ns = p.Nameservers
	} else {
		ns = []string{"ns1." + apex}
	}
	for i := range ns {
		ns[i] = dns.Fqdn(ns[i])
	}
	rname = p.Rname
	if rname == "" {
		rname = "hostmaster." + apex
	}
	return ns, dns.Fqdn(rname)
}
