/*
 * Copyright (c) 2026 Johan Stenstam, johani@johani.org
 *
 * Churning an existing zone instead of regenerating it.
 *
 * The use case is a fixture that MOVES: an RPZ zone whose rules change a little
 * every few minutes, or a large zone that produces a small IXFR. What matters
 * is not that the new zone is random but that the DELTA is small and the whole
 * thing is reproducible -- so the churn is seeded from the zone name and the
 * serial it is replacing. A given input file therefore always produces the same
 * next file, which makes a chain of updates a replayable sequence of deltas
 * rather than a random walk.
 *
 * The zone file is the state. There is no sidecar recording what was generated,
 * which also means --update still works on a file that has been hand-edited.
 */

package main

import (
	"fmt"
	"math/rand"
	"os"
	"strings"

	"github.com/miekg/dns"
)

// generatedMarker is what this tool writes at the top of every file. --update
// refuses a file without it: rewriting a hand-written zone because of a typo in
// --outfile should take an explicit --force.
const generatedMarker = "Generated by " + appName

// ownerGroup is all the records at one owner name, kept together because churn
// operates on names, not on individual records: deleting one of a name's three
// records and leaving the rest is not a change anybody makes on purpose.
type ownerGroup struct {
	Owner   string
	Records []string
}

// parsedZone is an existing zone file, split into the apex bookkeeping this
// tool regenerates and the body it churns.
type parsedZone struct {
	Serial uint32
	Body   []ownerGroup
}

// Mutator is the per-generator half of an update: the back half knows how much
// to change and which names to touch, and the generator knows what a name in
// ITS kind of zone should contain.
type Mutator interface {
	// NewEntry invents a name that is not in the zone yet, with its records.
	NewEntry(rng *rand.Rand, taken map[string]bool) (owner string, records []string)
	// Remake returns different records for a name that stays. It is given the
	// records the name holds now, because a "change" that happens to pick the
	// same value again is not a change: the churn percentage would then be a
	// claim rather than a fact.
	Remake(rng *rand.Rand, owner string, current []string) []string
}

// readExistingZone parses a zone file this tool previously wrote.
func readExistingZone(path, origin string, force bool) (*parsedZone, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("--update needs an existing zone file: %v", err)
	}
	if !strings.Contains(firstLine(string(data)), generatedMarker) && !force {
		return nil, fmt.Errorf("%s was not written by %s (no %q marker); "+
			"pass --force to rewrite it anyway", path, appName, generatedMarker)
	}

	pz := &parsedZone{}
	byOwner := map[string]int{}
	zp := dns.NewZoneParser(strings.NewReader(string(data)), origin, path)
	for rr, ok := zp.Next(); ok; rr, ok = zp.Next() {
		if soa, isSOA := rr.(*dns.SOA); isSOA {
			pz.Serial = soa.Serial
			continue
		}
		// The apex NS set is regenerated from config, not churned.
		if rr.Header().Name == origin && rr.Header().Rrtype == dns.TypeNS {
			continue
		}
		owner := rr.Header().Name
		idx, seen := byOwner[owner]
		if !seen {
			pz.Body = append(pz.Body, ownerGroup{Owner: owner})
			idx = len(pz.Body) - 1
			byOwner[owner] = idx
		}
		pz.Body[idx].Records = append(pz.Body[idx].Records, rr.String())
	}
	if err := zp.Err(); err != nil {
		return nil, fmt.Errorf("parsing %s: %v", path, err)
	}
	if pz.Serial == 0 {
		return nil, fmt.Errorf("%s has no SOA, so there is no serial to advance", path)
	}
	return pz, nil
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

// previousSerialOf returns the SOA serial of an existing zone file, or 0 if
// there is no readable zone there.
//
// Unlike readExistingZone this does NOT require the generated marker and does
// not care about the body: it is asked on the plain regenerate path, where the
// only question is what serial must be beaten. A file we cannot read is not an
// error here -- it just means there is no floor to respect.
func previousSerialOf(path, origin string) uint32 {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	zp := dns.NewZoneParser(strings.NewReader(string(data)), origin, path)
	for rr, ok := zp.Next(); ok; rr, ok = zp.Next() {
		if soa, isSOA := rr.(*dns.SOA); isSOA {
			return soa.Serial
		}
	}
	return 0
}

// churn applies percent% of change to the body, split between removing names,
// changing what a name holds, and adding names that were not there.
//
// The three-way split matters for the shape of the resulting IXFR: a pure-add
// churn grows the zone without bound over repeated runs, and a pure-delete one
// empties it. Splitting evenly keeps the zone the same size, so an operator can
// run this in a loop for a day and still recognise the zone at the end.
func churn(body []ownerGroup, percent float64, m Mutator, rng *rand.Rand) ([]ownerGroup, string) {
	n := len(body)
	total := int(float64(n)*percent/100.0 + 0.5)
	if total < 1 {
		total = 1
	}
	if total > n {
		total = n
	}
	// Adds equal removes so the zone neither grows nor shrinks over repeated
	// updates; the remainder goes to modifications, which are size-neutral.
	// Giving the remainder to adds instead (total - nDel - nMod) made every
	// churn grow the zone by up to two names, which over a day of RPZ updates
	// is slow drift rather than the stable size the docs claim.
	nDel := total / 3
	nAdd := nDel
	nMod := total - nDel - nAdd

	taken := make(map[string]bool, n)
	for _, g := range body {
		taken[g.Owner] = true
	}

	// A delegation is not churnable content. Remaking a cut point would replace
	// its NS with ordinary records, and deleting it would strand its glue and
	// the occluded name beneath it as ordinary data -- in both cases the zone
	// stays parseable but stops being the fixture --delegations produced. So
	// cuts, and everything below them, are held out of the victim set.
	protected := make([]string, 0, 4)
	for _, g := range body {
		for _, r := range g.Records {
			if f := strings.Fields(r); len(f) >= 4 && f[3] == "NS" {
				protected = append(protected, g.Owner)
				break
			}
		}
	}
	isProtected := func(owner string) bool {
		for _, p := range protected {
			if owner == p || strings.HasSuffix(owner, "."+p) {
				return true
			}
		}
		return false
	}

	// Choose the victims up front, by permutation, so no name is both modified
	// and deleted and the choice does not depend on iteration order.
	perm := rng.Perm(n)
	victims := make([]int, 0, len(perm))
	for _, i := range perm {
		if !isProtected(body[i].Owner) {
			victims = append(victims, i)
		}
	}
	del := map[int]bool{}
	mod := map[int]bool{}
	for i := 0; i < nDel && i < len(victims); i++ {
		del[victims[i]] = true
	}
	for i := nDel; i < nDel+nMod && i < len(victims); i++ {
		mod[victims[i]] = true
	}

	out := make([]ownerGroup, 0, n+nAdd)
	for i, g := range body {
		switch {
		case del[i]:
			continue
		case mod[i]:
			out = append(out, ownerGroup{Owner: g.Owner, Records: m.Remake(rng, g.Owner, g.Records)})
		default:
			out = append(out, g)
		}
	}
	added := 0
	for added < nAdd {
		owner, recs := m.NewEntry(rng, taken)
		if owner == "" {
			break // the generator has run out of names to invent
		}
		taken[owner] = true
		out = append(out, ownerGroup{Owner: owner, Records: recs})
		added++
	}

	return out, fmt.Sprintf("churned %d name(s) of %d: %d removed, %d changed, %d added",
		nDel+nMod+added, n, nDel, nMod, added)
}

// flatten turns owner groups back into the flat record list a ZoneSpec holds.
func flatten(groups []ownerGroup) []string {
	var out []string
	for _, g := range groups {
		out = append(out, g.Records...)
	}
	return out
}

// applyUpdate is the shared path: read, churn, and hand back a body plus the
// serial that must go with it.
func applyUpdate(path, zone string, percent float64, force bool, m Mutator) ([]string, uint32, error) {
	pz, err := readExistingZone(path, zone, force)
	if err != nil {
		return nil, 0, err
	}
	// Seeding from the OLD serial is what makes the chain reproducible: the
	// same input file always churns into the same output file.
	rng := newRand(zone, "update", fmt.Sprint(pz.Serial), fmt.Sprint(percent))
	groups, summary := churn(pz.Body, percent, m, rng)
	fmt.Println(summary)
	return flatten(groups), pz.Serial, nil
}
