/*
 * Copyright (c) 2026 Johan Stenstam, johani@johani.org
 *
 * The currency between the generators and everything downstream of them.
 *
 * A generator's whole job is to decide what zones exist and what is in them.
 * Everything after that -- create the keys, read back the DS, splice
 * delegations into parents, render, write atomically, emit the tdns-auth
 * block -- is identical whether the zones came from an algorithm matrix, a
 * 100,000-name tree or a list of RPZ rules. That shared half lives here, and
 * the generators produce nothing but a ZoneSet.
 *
 * This is why an unsigned generator needs no API server at all: if no zone in
 * the set names a policy, the keystore is never contacted.
 */

package main

import (
	"fmt"
	"sort"
	"strings"
)

// ZoneSpec is one zone to be written.
type ZoneSpec struct {
	Name string // FQDN

	// Policy is the DNSSEC policy that signs it. Empty means unsigned, which
	// is not a degenerate case: RPZ zones are normally unsigned, and an
	// unsigned set never touches the keystore.
	Policy string

	// Comments are extra header lines, after the "Generated by" line.
	Comments []string

	// Records is the body: everything below the apex SOA and apex NS, already
	// fully qualified. The generator owns the ORDER, which is why this is an
	// opaque list rather than a set of typed fields -- different generators
	// want different orders and the golden output pins them.
	Records []string

	// Children are zones delegated from this one. The back half fills in their
	// NS and DS once the keystore has been asked; the generator only says which
	// zones are children, never what their DS is.
	Children []string

	// DS is filled in by the back half, not by the generator.
	DS []string
}

// PolicySpec is one DNSSEC policy to emit into the tdns-auth config.
type PolicySpec struct {
	Name    string
	KSKAlg  string
	ZSKAlg  string
	Mode    string
	KSKLife string
	ZSKLife string
}

// ZoneSet is a generator's entire output.
type ZoneSet struct {
	Nameservers []string
	Rname       string
	Zones       []ZoneSpec
	Policies    []PolicySpec

	// Apex is the top of the tree, for the delegation snippet printed at the
	// end. Empty for generators that produce a single standalone zone.
	Apex string

	// Serial is stamped on every zone in the set.
	Serial uint32
}

// NeedsKeys reports whether anything in the set is signed. When nothing is,
// the whole API-connection question never arises.
func (zs *ZoneSet) NeedsKeys() bool {
	for i := range zs.Zones {
		if zs.Zones[i].Policy != "" {
			return true
		}
	}
	return false
}

// Zone returns a pointer to the named zone, or nil.
func (zs *ZoneSet) Zone(name string) *ZoneSpec {
	for i := range zs.Zones {
		if zs.Zones[i].Name == name {
			return &zs.Zones[i]
		}
	}
	return nil
}

// The dnssec: guardrail key names.
//
// tdns#406 respelled every config key with hyphens and kept no alias for the
// old form. The daemon populates its config with a decoder that ignores any key
// it has no tag for, so the wrong spelling here is not an error -- the keys are
// simply dropped, large-algorithms comes out empty, and PQ zones are served
// without the guardrail that keeps their DNSKEY responses answerable. Nothing
// reports it. That is why these live in one place and why the generated file
// states which spelling it used.
const (
	keyLargeAlgorithms = "large-algorithms"
	keySplitAlgorithms = "split-algorithms"
)

// Render produces one zone file.
//
// The shape is fixed here rather than in each generator so that every zone this
// tool writes reads the same way: provenance, then the apex, then the body the
// generator chose, then the delegations.
func (zs *ZoneSet) Render(z *ZoneSpec, d *DefaultsConf) string {
	var b strings.Builder
	fmt.Fprintf(&b, "; Generated by %s -- do not edit by hand.\n", appName)
	for _, c := range z.Comments {
		fmt.Fprintf(&b, "; %s\n", c)
	}
	fmt.Fprintf(&b, "%s\t%d\tIN\tSOA\t%s %s ( %d %d %d %d %d )\n",
		z.Name, d.TTL, zs.Nameservers[0], zs.Rname, zs.Serial,
		d.SOA.Refresh, d.SOA.Retry, d.SOA.Expire, d.SOA.Minimum)
	for _, ns := range zs.Nameservers {
		fmt.Fprintf(&b, "%s\t%d\tIN\tNS\t%s\n", z.Name, d.TTL, ns)
	}
	for _, r := range z.Records {
		fmt.Fprintf(&b, "%s\n", r)
	}
	if len(z.Children) > 0 {
		b.WriteString("\n")
		for _, cn := range z.Children {
			child := zs.Zone(cn)
			for _, ns := range zs.Nameservers {
				fmt.Fprintf(&b, "%s\t%d\tIN\tNS\t%s\n", cn, d.TTL, ns)
			}
			if child == nil {
				continue
			}
			for _, ds := range child.DS {
				fmt.Fprintf(&b, "%s\t%d\tIN\tDS\t%s\n", cn, d.TTL, ds)
			}
		}
	}
	return b.String()
}

// AuthConfig renders the tdns-auth block: the policies the set needs, the
// derived algorithm lists, and one zone declaration per zone.
func (zs *ZoneSet) AuthConfig(c *Config) string {
	z := &c.Zonegen
	d := &z.Defaults
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by %s -- do not edit by hand.\n", appName)
	fmt.Fprintf(&b, "#\n")
	fmt.Fprintf(&b, "# Pull this into the tdns-auth config with an opt-in include:\n")
	fmt.Fprintf(&b, "#\n")
	fmt.Fprintf(&b, "#   include:\n")
	fmt.Fprintf(&b, "#      - file:   %s\n", c.Zonegen.Output.ConfigFile)
	fmt.Fprintf(&b, "#        merge:  true\n")
	fmt.Fprintf(&b, "#\n")
	fmt.Fprintf(&b, "# merge: true is required. A bare include REPLACES the server's own\n")
	fmt.Fprintf(&b, "# zones: list with the one below instead of adding to it, which would\n")
	fmt.Fprintf(&b, "# stop every other zone on the server from being served.\n")
	fmt.Fprintf(&b, "#\n")
	fmt.Fprintf(&b, "# Needs a tdns with opt-in include merging (tdns#404). On an older one\n")
	fmt.Fprintf(&b, "# the map form is not understood at all, so this must be pasted in by\n")
	fmt.Fprintf(&b, "# hand rather than included.\n")
	// Named explicitly because the daemon silently ignores a config key it has
	// no tag for. If these keys are the wrong spelling for the tdns being run,
	// nothing reports it -- the guardrail is simply absent.
	fmt.Fprintf(&b, "#\n# dnssec guardrail keys are spelled %q / %q here (tdns#406).\n",
		keyLargeAlgorithms, keySplitAlgorithms)
	fmt.Fprintf(&b, "# If the server ignores them, its key spelling differs and zonegen\n")
	fmt.Fprintf(&b, "# needs updating.\n\n")

	if len(zs.Policies) > 0 {
		b.WriteString("dnssec:\n")
		// Derived from the RESOLVED policy set rather than from whatever the
		// generator happened to be iterating over, so a policy written by hand
		// contributes to these lists exactly like a generated one.
		if large := largeAlgorithmsOf(zs.Policies); len(large) > 0 {
			fmt.Fprintf(&b, "   %s:  [ %s ]\n", keyLargeAlgorithms, strings.Join(large, ", "))
		}
		if split := splitAlgorithmsOf(zs.Policies); len(split) > 0 {
			fmt.Fprintf(&b, "   %s:\n", keySplitAlgorithms)
			ksks := make([]string, 0, len(split))
			for k := range split {
				ksks = append(ksks, k)
			}
			sort.Strings(ksks)
			for _, ksk := range ksks {
				fmt.Fprintf(&b, "      %s:  [ %s ]\n", ksk, strings.Join(split[ksk], ", "))
			}
		}
		b.WriteString("   policies:\n")
		for _, p := range zs.Policies {
			fmt.Fprintf(&b, "      %s:\n", p.Name)
			fmt.Fprintf(&b, "         algorithm:  %s\n", p.ZSKAlg)
			fmt.Fprintf(&b, "         mode:       %s\n", p.Mode)
			b.WriteString("         ksk:\n")
			fmt.Fprintf(&b, "            algorithm:  %s\n", p.KSKAlg)
			fmt.Fprintf(&b, "            lifetime:   %s\n", p.KSKLife)
			b.WriteString("         zsk:\n")
			fmt.Fprintf(&b, "            algorithm:  %s\n", p.ZSKAlg)
			fmt.Fprintf(&b, "            lifetime:   %s\n", p.ZSKLife)
			b.WriteString("         csk:\n")
			b.WriteString("            lifetime:  none\n")
			// Required by tdns-auth: a policy without sigvalidity.default is
			// rejected at parse time and every zone bound to it is unusable.
			b.WriteString("         sigvalidity:\n")
			fmt.Fprintf(&b, "            default:  %s\n", z.SigValidity.Default)
			fmt.Fprintf(&b, "            dnskey:   %s\n", z.SigValidity.Dnskey)
			fmt.Fprintf(&b, "            ds:       %s\n", z.SigValidity.DS)
		}
	}

	b.WriteString("\nzones:\n")
	for i := range zs.Zones {
		zone := &zs.Zones[i]
		fmt.Fprintf(&b, "   - name:          %s\n", zone.Name)
		fmt.Fprintf(&b, "     type:          %s\n", d.Zone.Type)
		fmt.Fprintf(&b, "     zonefile:      %s\n", c.ZonefilePath(zone.Name))
		fmt.Fprintf(&b, "     store:         %s\n", d.Zone.Store)
		if len(d.Zone.Options) > 0 && zone.Policy != "" {
			fmt.Fprintf(&b, "     options:       [ %s ]\n", strings.Join(d.Zone.Options, ", "))
		}
		if zone.Policy != "" {
			fmt.Fprintf(&b, "     dnssecpolicy:  %s\n", zone.Policy)
		}
	}
	return b.String()
}

// DelegationSnippet is what the operator pastes into the parent of the apex --
// typically a zone served by something else entirely. This tool prints it and
// stops: reaching into another nameserver's zone files is not its business.
func (zs *ZoneSet) DelegationSnippet() string {
	if zs.Apex == "" {
		return ""
	}
	var b strings.Builder
	fmt.Fprintf(&b, "; Add to the parent of %s, then reload it.\n", zs.Apex)
	for _, ns := range zs.Nameservers {
		fmt.Fprintf(&b, "%s\tIN\tNS\t%s\n", zs.Apex, ns)
	}
	apex := zs.Zone(zs.Apex)
	if apex == nil || len(apex.DS) == 0 {
		b.WriteString("; (no DS: the apex zone has no KSK in the keystore yet)\n")
		return b.String()
	}
	for _, ds := range apex.DS {
		fmt.Fprintf(&b, "%s\tIN\tDS\t%s\n", zs.Apex, ds)
	}
	return b.String()
}

// largeAlgorithmsOf and splitAlgorithmsOf derive the two dnssec: lists from the
// resolved policies. See the design note in AuthConfig: deriving from policies
// rather than from a generator's own inputs is what keeps a hand-written policy
// from being invisible to them.
func largeAlgorithmsOf(policies []PolicySpec) []string {
	seen := map[string]bool{}
	for _, p := range policies {
		for _, name := range []string{p.KSKAlg, p.ZSKAlg} {
			if a, ok := lookupAlg(name); ok && a.IsLarge() {
				seen[a.Name] = true
			}
		}
	}
	return sortedKeys(seen)
}

func splitAlgorithmsOf(policies []PolicySpec) map[string][]string {
	out := map[string]map[string]bool{}
	for _, p := range policies {
		if p.KSKAlg == p.ZSKAlg {
			continue
		}
		if out[p.KSKAlg] == nil {
			out[p.KSKAlg] = map[string]bool{}
		}
		out[p.KSKAlg][p.ZSKAlg] = true
	}
	res := map[string][]string{}
	for ksk, zsks := range out {
		res[ksk] = sortedKeys(zsks)
	}
	return res
}

// defaultGlueAddress is what a synthesised in-bailiwick nameserver gets. It is
// in the documentation range: a generated zone should not point anywhere real.
const defaultGlueAddress = "192.0.2.53"

// AddGlue gives every in-bailiwick nameserver an address in whichever zone of
// the set actually holds it.
//
// This is not tidiness. A zone whose apex NS names a host inside the zone, with
// no address for that host, is one BIND refuses to load outright ("has no
// address records"). It parses perfectly well, which is why the round-trip
// tests here did not catch it and named-checkzone did -- worth remembering:
// "parses" and "loads" are different claims.
//
// Out-of-bailiwick nameservers are left alone: their addresses are somebody
// else's zone's business, and inventing one here would be wrong.
func (zs *ZoneSet) AddGlue(d *DefaultsConf) {
	for _, ns := range zs.Nameservers {
		// The enclosing zone is the longest zone name that is a suffix of the
		// nameserver's name; anything else would put the glue in a zone that is
		// not authoritative for it.
		best := -1
		for i := range zs.Zones {
			zn := zs.Zones[i].Name
			if ns == zn || strings.HasSuffix(ns, "."+zn) {
				if best == -1 || len(zn) > len(zs.Zones[best].Name) {
					best = i
				}
			}
		}
		if best == -1 {
			continue // out of bailiwick for every zone here
		}
		if zs.Zones[best].hasAddressFor(ns) {
			continue
		}
		zs.Zones[best].Records = append(zs.Zones[best].Records,
			fmt.Sprintf("%s\t%d\tIN\tA\t%s", ns, d.TTL, defaultGlueAddress))
	}
}

// hasAddressFor reports whether the zone already carries an A or AAAA at name.
func (z *ZoneSpec) hasAddressFor(name string) bool {
	for _, r := range z.Records {
		f := strings.Fields(r)
		if len(f) >= 4 && f[0] == name && (f[3] == "A" || f[3] == "AAAA") {
			return true
		}
	}
	return false
}
