VERSION=`cat ../VERSION`
BRANCH:=`git rev-parse --abbrev-ref HEAD`
COMMIT:=`git describe --dirty=+WiP --always`
APPDATE=`date +"%Y-%m-%d-%H:%M"`

# GOFLAGS:=-v -ldflags "-X foo.bar=BAZ"
GOFLAGS:=-v

GOOS ?= $(shell uname -s | tr A-Z a-z)

default: ${PROG}

${PROG}: build

PROGS_WITH_VERSION := traffic-server

build:
	/bin/sh ../utils/make-version.sh $(VERSION)-$(BRANCH)-$(COMMIT) $(APPDATE) $(PROG)
	$(GO) build $(GOFLAGS) -o ${PROG}

test:
	$(GO) test -v -cover

# install:
# 	install -s -b -c ${PROG} /usr/local/bin/

lint:
	go fmt ./...
	go vet ./...
	staticcheck ./...
	gosec ./...
	golangci-lint run

.PHONY: build clean
